pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                bat '@echo off'
                bat '@echo "Hello World"'
                bat 'set'
            }
        }
    }
}